# Custom Language File for Launcher Customizer

[ejs.app]
title = "LCY-ONLINE"

[ejs.landing]
mediaGitHubURL = "https://cafe.naver.com/lcyonline"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/fHfpWbwUd6"

[ejs.settings]
sourceGithubLink = "https://github.com/mmumg255/LCY-ONLINE"
supportLink = "https://github.com/mmumg255/LCY-ONLINE/issues"

[ejs.welcome]
welcomeHeader = "행운 온라인에 오신 것을 환영합니다!"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
 